[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:may indicate binary incompatibility:RuntimeWarning',
]
log_cli = true
log_cli_level = "DEBUG"
